packages:
  - '.'

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - vite@8.1.3
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - sharp
