allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - electron@44.4.1
  - '@types/node@22.20.3'
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - sharp
